# Generated by Django 4.1 on 2022-08-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=12)),
                ('Age', models.SmallIntegerField()),
                ('Location', models.CharField(max_length=30)),
                ('Phone_number', models.CharField(max_length=10)),
                ('Interests', models.CharField(max_length=30)),
            ],
        ),
    ]
