# Generated by Django 4.1 on 2022-08-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_image', models.ImageField(upload_to='')),
                ('Roll_number', models.IntegerField()),
                ('Student_email', models.EmailField(max_length=254)),
                ('Student_phone_number', models.CharField(max_length=15)),
                ('Student_location', models.CharField(max_length=30)),
                ('Student_college', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='visitor',
            name='Phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
