# Generated by Django 4.1 on 2022-08-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_alter_visitor_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('duration', models.IntegerField()),
                ('year', models.DateField()),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='Student_fullname',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
