# Generated by Django 4.1 on 2022-08-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_course_student_student_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Course_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=50),
        ),
    ]
