# Generated by Django 4.1 on 2022-08-23 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='Schedule_id',
            field=models.CharField(max_length=40),
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trainer_id', models.CharField(max_length=40)),
                ('Full_name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_number', models.CharField(max_length=15)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Trainer_Course', to='home.course')),
            ],
        ),
    ]
