# Generated by Django 4.1 on 2022-08-23 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_trainer_trainers_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='Trainer_id',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fee_id', models.CharField(max_length=10)),
                ('Amount', models.PositiveIntegerField()),
                ('Balance', models.PositiveIntegerField()),
                ('Status', models.PositiveIntegerField()),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fees_Course', to='home.course')),
            ],
        ),
    ]
