# Generated by Django 4.1 on 2022-08-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_trainer_trainer_id_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='Status',
            field=models.CharField(max_length=40),
        ),
    ]
