# Generated by Django 4.1 on 2022-08-23 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_fees_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_id', models.CharField(max_length=10)),
                ('Status', models.CharField(max_length=40)),
                ('Payment_date', models.DateField()),
                ('Due_date', models.DateTimeField()),
                ('Amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Course_Amount', to='home.fees')),
                ('Student_roll_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student_Payment', to='home.student')),
            ],
        ),
    ]
